### ISSUE TITLE
Numerous issues from xron89

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#25]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=330 (author: xron89) at Dec 12, 2012 at 13:51 UTC**

Massive bug, you can change kits more than 1 time per life and you can end up with iron armour, and a bow from archer. Eek!

**Comment by lol768** [comment]
Additional comment from xron89:

> two things -
> Potions dont seem to be adding to kits right and players with a kit permission can use the kit via a sign, E.g having > the kit heavy lets use use all the other kits too :S using signs
> 
> I see lots of people with potions issues could you maybe post an example config with a potion because you have the id e.g. 373:8025 then how do you add an ammount 373:8025:64? :S
> 
> Note the ninja kit doesnt also work (potions side of things)

**Comment by lol768** [comment]
All issues should really follow this format: https://github.com/np98765/BattleKits/issues/1

Regardless, I have some answers for you. See this issue: https://github.com/np98765/BattleKits/issues/26 for information on sorting out data values.

In your global.yml, signs can be setup to ignore permissions. I need your config files to help you effectively.

There was an issue with the ninja kit, I've fixed the syntax error and the potion issues here:
http://dev.bukkit.org/server-mods/battlekits/forum/kits-forum/45072-ninja/?post=3

I've only just fixed the potions, so you may wish to re-download.

I need your config file and server log to really investigate the bugs you mentioned in your first comment:

> Massive bug, you can change kits more than 1 time per life and you can end up with iron armour, and a bow from archer. Eek!

**Comment by xron89** [comment]
Hi, this is my config 
http://pastebin.com/DjYbjckN

I have no log errors they can also drop items from kits, so they become archer drop the bow become heavy pickup the bow

**Comment by lol768** [comment]
Kit config would be helpful.

You can turn off item drops with the restriction system.

**Comment by xron89** [comment]
Here is my log anyway - http://pastebin.com/SSwxHxJ4
here is my kit file - http://pastebin.com/RxV8Jtsx

Updated my config to enable restrictions nothing has changed
New config - http://pastebin.com/s41X7x0h

You still have access to my cPanel from before if you need to look at anything when i'm not here to paste them to you ^^
If you have skype we could talk on there i'm online 24/7 on skype could maybe give you faster answers :)

**Comment by lol768** [comment]
I'll take a more in-depth look later today. You should be aware that 
restrictions are handled by permissions, I'll put some more info on that 
on the DBO page.

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/25#issuecomment-11329792

> You still have access to my cPanel from before if you need to look at anything when i'm not here to paste them to you ^^
> If you have skype we could talk on there i'm online 24/7 on skype could maybe give you faster answers :) 

I get `Username or password was incorrect.` when trying to login.

**Comment by xron89** [comment]
add my skype - xron89 or email me sam@xronn.co.uk so I can send you the correct info

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/25#issuecomment-11345525

> add my skype - xron89 or email me sam@xronn.co.uk so I can send you the correct info 

http://dev.bukkit.org/home/send-private-message/

**Comment by xron89** [comment]
sent

**Comment by lol768** [comment]
@xron89 https://github.com/np98765/BattleKits/issues/25#issuecomment-11353230

> sent

Which server needs sorting?

**Comment by xron89** [comment]
the one with the most slots, 2nd one in the list, if you join and try you can swap kits even though you are already a kit

**Comment by lol768** [comment]
I'll look into it tonight

**Comment by xron89** [comment]
Thanks, I will be working on adding plugins and building things myself so I would be greatful if you could use the stop/restart button on the cpanel to gravefully stop the server 

thanks

**Comment by xron89** [comment]
Loads of battlekit errors in my log now information is the same, if you could take a look ^^

**Comment by xron89** [comment]
I think this plugin stops your players from building in other worlds so I might have to remove it

**Comment by lol768** [comment]
https://github.com/np98765/BattleKits/issues/31
Merged into new issue
